/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoiRouteImport } from './routes/roi'
import { Route as ReasoningRouteImport } from './routes/reasoning'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'

const RoiRoute = RoiRouteImport.update({
  id: '/roi',
  path: '/roi',
  getParentRoute: () => rootRouteImport,
} as any)
const ReasoningRoute = ReasoningRouteImport.update({
  id: '/reasoning',
  path: '/reasoning',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/memory': typeof MemoryRoute
  '/reasoning': typeof ReasoningRoute
  '/roi': typeof RoiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/memory': typeof MemoryRoute
  '/reasoning': typeof ReasoningRoute
  '/roi': typeof RoiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/memory': typeof MemoryRoute
  '/reasoning': typeof ReasoningRoute
  '/roi': typeof RoiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/audit' | '/memory' | '/reasoning' | '/roi'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/audit' | '/memory' | '/reasoning' | '/roi'
  id: '__root__' | '/' | '/audit' | '/memory' | '/reasoning' | '/roi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  MemoryRoute: typeof MemoryRoute
  ReasoningRoute: typeof ReasoningRoute
  RoiRoute: typeof RoiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/roi': {
      id: '/roi'
      path: '/roi'
      fullPath: '/roi'
      preLoaderRoute: typeof RoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reasoning': {
      id: '/reasoning'
      path: '/reasoning'
      fullPath: '/reasoning'
      preLoaderRoute: typeof ReasoningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  MemoryRoute: MemoryRoute,
  ReasoningRoute: ReasoningRoute,
  RoiRoute: RoiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
